// src/cli/commands/analyze.ts
import { Command } from "commander";
import { existsSync } from "fs";
import { readFile } from "fs/promises";
import { spawn } from "child_process";
import path from "path";

const SYSTEM_PROMPT = `You are helping create a converter.py script that transforms megamaid accessibility tree snapshots into clean Markdown.

## Context

The user has run \`megamaid suck\` to crawl a website and save accessibility tree snapshots to disk. Each snapshot is a JSON file containing:

- \`tree\`: A text outline of the page's accessibility tree (indented, with element IDs like \`[0-155]\`)
- \`urlMap\`: A mapping of element IDs to URLs
- \`imageMap\`: A mapping of element IDs to local image paths
- \`url\`: The original page URL
- \`title\`: The page title

The \`site.json\` manifest lists all captured pages.

## Your Task

1. **Read \`site.json\`** from the provided directory to understand the crawl
2. **Read 2-3 sample snapshots** — pick the first, one from the middle, and the last to catch structural variation
3. **Analyze the tree structure** to identify:
   - Where the page title lives (usually \`heading level=1\`)
   - Where main content starts and ends
   - What to skip: navigation, sidebar, footer, cookie banners, feedback widgets, breadcrumbs
   - How links appear in the tree (element IDs that map to \`urlMap\`)
   - How images appear (element IDs that map to \`imageMap\`)
4. **Write \`converter.py\`** in the directory that:
   - Is self-contained Python 3 (no pip dependencies — stdlib only)
   - Reads snapshot JSON files from \`snapshots/\`
   - Converts each snapshot's tree to clean Markdown
   - Replaces element IDs with real URLs from \`urlMap\`
   - Replaces image element IDs with paths from \`imageMap\`, prefixed with \`../\` (since Markdown files go into \`markdown/\` but image paths in \`imageMap\` are relative to the output root, e.g. \`images/page/img-001.png\` → \`../images/page/img-001.png\`)
   - Has a \`main()\` with argparse: \`input_dir\`, \`--out\`, \`--chunk\`, \`--chunk-size\`, \`--only\`, \`--dry-run\`
   - Generates an \`index.md\` summary table
   - Handles \`--chunk\` with heading-aware splitting and YAML frontmatter per chunk
   - Handles \`--only\` to convert specific pages
   - Handles \`--dry-run\` to convert one page and print to stdout
   - Skips pages gracefully on error (log and continue)
5. **Run it** against one sample: \`python3 <dir>/converter.py <dir> --dry-run\`

## Converter Script Template

The script should follow this general structure:

\`\`\`python
#!/usr/bin/env python3
"""Site-specific converter for <sitename> — generated by Claude"""

import json, re, os, sys, argparse
from pathlib import Path
from datetime import datetime

def parse_tree_line(line: str) -> dict:
    """Parse a single tree line into components (indent, element_id, role, name, level)."""
    # ...

def convert(snapshot: dict, image_dir: str) -> str:
    """Convert a single snapshot to Markdown."""
    tree = snapshot["tree"]
    url_map = snapshot.get("urlMap", {})
    image_map = snapshot.get("imageMap", {})
    lines = tree.split("\\n")
    md_parts = []
    # Site-specific logic here
    return "\\n".join(md_parts)

def generate_index(site: dict, out_dir: Path) -> str:
    """Generate index.md summary."""
    # ...

def chunk_markdown(markdown: str, chunk_size: int = 50000) -> list[dict]:
    """Split markdown into heading-aware chunks."""
    # ...

def main():
    parser = argparse.ArgumentParser(description="Convert megamaid snapshots to Markdown")
    parser.add_argument("input_dir", help="Directory with site.json and snapshots/")
    parser.add_argument("--out", default=None, help="Output dir (default: input_dir/markdown/)")
    parser.add_argument("--chunk", action="store_true", help="Enable chunked output")
    parser.add_argument("--chunk-size", type=int, default=50000, help="Target chunk size")
    parser.add_argument("--only", help="Convert only these pages (comma-separated)")
    parser.add_argument("--dry-run", action="store_true", help="Convert first page, print to stdout")
    args = parser.parse_args()
    # ...

if __name__ == "__main__":
    main()
\`\`\`

## Important Guidelines

- The tree text uses indentation to show hierarchy. Each line has format: \`[frameOrdinal-backendNodeId] role: "name"\` with optional properties like \`level=1\`
- Navigation elements typically have role \`navigation\`. Skip these.
- The main content is usually between the first \`heading level=1\` and the first \`contentinfo\` (footer) or \`navigation\` after content
- Links in the tree text look like \`[0-155] link: "Click here"\` — the ID \`0-155\` maps to a URL in \`urlMap\`
- Images look like \`[0-200] image: "Alt text"\` — the ID \`0-200\` maps to a local image path in \`imageMap\`. Since Markdown output goes into \`<dir>/markdown/\` but imageMap paths are relative to \`<dir>/\` (e.g. \`images/page/img-001.png\`), you MUST prefix with \`../\` so the reference resolves correctly: \`![alt](../images/page/img-001.png)\`
- Make the converter robust: if a snapshot has unexpected structure, log a warning and skip it rather than crashing
- Output filenames should be FLAT (not nested subdirectories). Use the snapshot filename stem as the markdown filename, e.g. \`snapshots/documentation-page-abc-slug.json\` → \`markdown/documentation-page-abc-slug.md\`
- Do NOT ask questions or wait for input. Analyze the snapshots and write converter.py immediately.
- Do NOT check for existing markdown files. Always write a fresh converter that reconverts everything.
- The converter must be complete and working. Test it with --dry-run before finishing.`;

export function createAnalyzeCommand(): Command {
  const cmd = new Command("analyze")
    .description("Generate a site-specific converter.py by analyzing snapshots with Claude")
    .addHelpText("after", `
Prerequisites:
  Run 'megamaid suck' first to capture snapshots into a directory.
  Requires Claude Code CLI ('claude') installed and authenticated.

Examples:
  megamaid analyze ./output
  megamaid analyze ./output --model sonnet
  megamaid analyze ./output --print-prompt  # see what gets sent to Claude

What it does:
  1. Reads site.json and 2-3 sample snapshots
  2. Sends them to Claude with instructions to write a converter.py
  3. Claude writes converter.py in the directory and tests it with --dry-run
`)
    .argument("[dir]", "Directory containing site.json and snapshots/ (output of suck)", "./output")
    .option("--model <model>", "Claude model to use", "sonnet")
    .option("--print-prompt", "Print the prompt that would be sent to Claude and exit")
    .action(async (dir: string, opts) => {
      try {
        const inputDir = path.resolve(dir);

        // Validate directory
        const siteJsonPath = path.join(inputDir, "site.json");
        if (!existsSync(siteJsonPath)) {
          console.error(`No site.json found in ${inputDir}. Run 'megamaid suck' first.`);
          process.exit(1);
        }

        const snapshotsDir = path.join(inputDir, "snapshots");
        if (!existsSync(snapshotsDir)) {
          console.error(`No snapshots/ directory found in ${inputDir}. Run 'megamaid suck' first.`);
          process.exit(1);
        }

        // Check claude CLI is available
        const claudeAvailable = await checkClaude();
        if (!claudeAvailable && !opts.printPrompt) {
          console.error("Claude Code CLI ('claude') not found. Install it from https://claude.ai/code");
          process.exit(1);
        }

        // Build the user prompt with the directory path
        const userPrompt = `Analyze the snapshots in ${inputDir} and write a converter.py. The site.json is at ${siteJsonPath} and snapshots are in ${snapshotsDir}/. After writing the converter, test it with: python3 ${inputDir}/converter.py ${inputDir} --dry-run`;

        if (opts.printPrompt) {
          console.log("=== SYSTEM PROMPT ===\n");
          console.log(SYSTEM_PROMPT);
          console.log("\n=== USER PROMPT ===\n");
          console.log(userPrompt);
          return;
        }

        console.log(`Analyzing snapshots in ${inputDir}...`);
        console.log(`Using model: ${opts.model}\n`);

        const exitCode = await runClaude(userPrompt, opts.model);

        if (exitCode !== 0) {
          console.error(`\nClaude exited with code ${exitCode}.`);
          process.exit(1);
        }

        // Check if converter.py was created
        const converterPath = path.join(inputDir, "converter.py");
        if (existsSync(converterPath)) {
          console.log(`\nconverter.py written to ${converterPath}`);
          console.log(`\nNext step: megamaid blow ${dir}`);
        } else {
          console.log(`\nNote: converter.py was not found at ${converterPath}.`);
          console.log(`You may need to run this again or write it manually.`);
        }
      } catch (err) {
        console.error(`Error: ${(err as Error).message}`);
        process.exit(1);
      }
    });

  return cmd;
}

async function checkClaude(): Promise<boolean> {
  return new Promise((resolve) => {
    const proc = spawn("claude", ["--version"], { stdio: "ignore" });
    proc.on("error", () => resolve(false));
    proc.on("close", (code) => resolve(code === 0));
  });
}

function runClaude(prompt: string, model: string): Promise<number> {
  return new Promise((resolve, reject) => {
    const args = [
      "-p", prompt,
      "--model", model,
      "--allowedTools", "Read,Write,Edit,Bash,Glob,Grep",
    ];
    const proc = spawn("claude", args, {
      stdio: ["ignore", "inherit", "inherit"],
    });
    proc.on("error", (err) => reject(new Error(`Failed to start Claude: ${err.message}`)));
    proc.on("close", (code) => resolve(code ?? 1));
  });
}
